// Mocks generated by Mockito 5.4.6 from annotations
// in frontend/test/unit/providers/assistant_conversation_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:typed_data' as _i8;

import 'package:frontend/models/document.dart' as _i3;
import 'package:frontend/models/thread.dart' as _i2;
import 'package:frontend/services/ai_service.dart' as _i4;
import 'package:frontend/services/document_service.dart' as _i7;
import 'package:frontend/services/thread_service.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeThread_0 extends _i1.SmartFake implements _i2.Thread {
  _FakeThread_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePaginatedThreads_1 extends _i1.SmartFake
    implements _i2.PaginatedThreads {
  _FakePaginatedThreads_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDocument_2 extends _i1.SmartFake implements _i3.Document {
  _FakeDocument_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AIService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAIService extends _i1.Mock implements _i4.AIService {
  @override
  _i5.Stream<_i4.ChatEvent> streamChat(
    String? threadId,
    String? message, {
    bool? artifactGeneration = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #streamChat,
              [threadId, message],
              {#artifactGeneration: artifactGeneration},
            ),
            returnValue: _i5.Stream<_i4.ChatEvent>.empty(),
            returnValueForMissingStub: _i5.Stream<_i4.ChatEvent>.empty(),
          )
          as _i5.Stream<_i4.ChatEvent>);

  @override
  _i5.Future<void> deleteMessage(String? threadId, String? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMessage, [threadId, messageId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [ThreadService].
///
/// See the documentation for Mockito's code generation for more information.
class MockThreadService extends _i1.Mock implements _i6.ThreadService {
  @override
  _i5.Future<List<_i2.Thread>> getThreads(String? projectId) =>
      (super.noSuchMethod(
            Invocation.method(#getThreads, [projectId]),
            returnValue: _i5.Future<List<_i2.Thread>>.value(<_i2.Thread>[]),
            returnValueForMissingStub: _i5.Future<List<_i2.Thread>>.value(
              <_i2.Thread>[],
            ),
          )
          as _i5.Future<List<_i2.Thread>>);

  @override
  _i5.Future<_i2.Thread> createThread(
    String? projectId,
    String? title, {
    String? provider,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createThread,
              [projectId, title],
              {#provider: provider},
            ),
            returnValue: _i5.Future<_i2.Thread>.value(
              _FakeThread_0(
                this,
                Invocation.method(
                  #createThread,
                  [projectId, title],
                  {#provider: provider},
                ),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.Thread>.value(
              _FakeThread_0(
                this,
                Invocation.method(
                  #createThread,
                  [projectId, title],
                  {#provider: provider},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Thread>);

  @override
  _i5.Future<_i2.Thread> getThread(String? threadId) =>
      (super.noSuchMethod(
            Invocation.method(#getThread, [threadId]),
            returnValue: _i5.Future<_i2.Thread>.value(
              _FakeThread_0(this, Invocation.method(#getThread, [threadId])),
            ),
            returnValueForMissingStub: _i5.Future<_i2.Thread>.value(
              _FakeThread_0(this, Invocation.method(#getThread, [threadId])),
            ),
          )
          as _i5.Future<_i2.Thread>);

  @override
  _i5.Future<void> deleteThread(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteThread, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.Thread> renameThread(String? threadId, String? title) =>
      (super.noSuchMethod(
            Invocation.method(#renameThread, [threadId, title]),
            returnValue: _i5.Future<_i2.Thread>.value(
              _FakeThread_0(
                this,
                Invocation.method(#renameThread, [threadId, title]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.Thread>.value(
              _FakeThread_0(
                this,
                Invocation.method(#renameThread, [threadId, title]),
              ),
            ),
          )
          as _i5.Future<_i2.Thread>);

  @override
  _i5.Future<_i2.PaginatedThreads> getGlobalThreads({
    int? page = 1,
    int? pageSize = 25,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getGlobalThreads, [], {
              #page: page,
              #pageSize: pageSize,
            }),
            returnValue: _i5.Future<_i2.PaginatedThreads>.value(
              _FakePaginatedThreads_1(
                this,
                Invocation.method(#getGlobalThreads, [], {
                  #page: page,
                  #pageSize: pageSize,
                }),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.PaginatedThreads>.value(
              _FakePaginatedThreads_1(
                this,
                Invocation.method(#getGlobalThreads, [], {
                  #page: page,
                  #pageSize: pageSize,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.PaginatedThreads>);

  @override
  _i5.Future<List<_i2.Thread>> getAssistantThreads() =>
      (super.noSuchMethod(
            Invocation.method(#getAssistantThreads, []),
            returnValue: _i5.Future<List<_i2.Thread>>.value(<_i2.Thread>[]),
            returnValueForMissingStub: _i5.Future<List<_i2.Thread>>.value(
              <_i2.Thread>[],
            ),
          )
          as _i5.Future<List<_i2.Thread>>);

  @override
  _i5.Future<_i2.Thread> createGlobalThread({
    String? title,
    String? projectId,
    String? modelProvider,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createGlobalThread, [], {
              #title: title,
              #projectId: projectId,
              #modelProvider: modelProvider,
            }),
            returnValue: _i5.Future<_i2.Thread>.value(
              _FakeThread_0(
                this,
                Invocation.method(#createGlobalThread, [], {
                  #title: title,
                  #projectId: projectId,
                  #modelProvider: modelProvider,
                }),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.Thread>.value(
              _FakeThread_0(
                this,
                Invocation.method(#createGlobalThread, [], {
                  #title: title,
                  #projectId: projectId,
                  #modelProvider: modelProvider,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.Thread>);

  @override
  _i5.Future<_i2.Thread> updateThreadMode(String? threadId, String? mode) =>
      (super.noSuchMethod(
            Invocation.method(#updateThreadMode, [threadId, mode]),
            returnValue: _i5.Future<_i2.Thread>.value(
              _FakeThread_0(
                this,
                Invocation.method(#updateThreadMode, [threadId, mode]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.Thread>.value(
              _FakeThread_0(
                this,
                Invocation.method(#updateThreadMode, [threadId, mode]),
              ),
            ),
          )
          as _i5.Future<_i2.Thread>);

  @override
  _i5.Future<_i2.Thread> associateWithProject(
    String? threadId,
    String? projectId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#associateWithProject, [threadId, projectId]),
            returnValue: _i5.Future<_i2.Thread>.value(
              _FakeThread_0(
                this,
                Invocation.method(#associateWithProject, [threadId, projectId]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.Thread>.value(
              _FakeThread_0(
                this,
                Invocation.method(#associateWithProject, [threadId, projectId]),
              ),
            ),
          )
          as _i5.Future<_i2.Thread>);

  @override
  _i5.Future<_i2.Thread> createAssistantThread({
    required String? title,
    String? description,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createAssistantThread, [], {
              #title: title,
              #description: description,
            }),
            returnValue: _i5.Future<_i2.Thread>.value(
              _FakeThread_0(
                this,
                Invocation.method(#createAssistantThread, [], {
                  #title: title,
                  #description: description,
                }),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.Thread>.value(
              _FakeThread_0(
                this,
                Invocation.method(#createAssistantThread, [], {
                  #title: title,
                  #description: description,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.Thread>);
}

/// A class which mocks [DocumentService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDocumentService extends _i1.Mock implements _i7.DocumentService {
  @override
  _i5.Future<_i3.Document> uploadDocument(
    String? projectId,
    List<int>? fileBytes,
    String? filename, {
    void Function(int, int)? onSendProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #uploadDocument,
              [projectId, fileBytes, filename],
              {#onSendProgress: onSendProgress},
            ),
            returnValue: _i5.Future<_i3.Document>.value(
              _FakeDocument_2(
                this,
                Invocation.method(
                  #uploadDocument,
                  [projectId, fileBytes, filename],
                  {#onSendProgress: onSendProgress},
                ),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i3.Document>.value(
              _FakeDocument_2(
                this,
                Invocation.method(
                  #uploadDocument,
                  [projectId, fileBytes, filename],
                  {#onSendProgress: onSendProgress},
                ),
              ),
            ),
          )
          as _i5.Future<_i3.Document>);

  @override
  _i5.Future<List<_i3.Document>> getDocuments(String? projectId) =>
      (super.noSuchMethod(
            Invocation.method(#getDocuments, [projectId]),
            returnValue: _i5.Future<List<_i3.Document>>.value(<_i3.Document>[]),
            returnValueForMissingStub: _i5.Future<List<_i3.Document>>.value(
              <_i3.Document>[],
            ),
          )
          as _i5.Future<List<_i3.Document>>);

  @override
  _i5.Future<_i3.Document> getDocumentContent(String? documentId) =>
      (super.noSuchMethod(
            Invocation.method(#getDocumentContent, [documentId]),
            returnValue: _i5.Future<_i3.Document>.value(
              _FakeDocument_2(
                this,
                Invocation.method(#getDocumentContent, [documentId]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i3.Document>.value(
              _FakeDocument_2(
                this,
                Invocation.method(#getDocumentContent, [documentId]),
              ),
            ),
          )
          as _i5.Future<_i3.Document>);

  @override
  _i5.Future<List<_i7.DocumentSearchResult>> searchDocuments(
    String? projectId,
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchDocuments, [projectId, query]),
            returnValue: _i5.Future<List<_i7.DocumentSearchResult>>.value(
              <_i7.DocumentSearchResult>[],
            ),
            returnValueForMissingStub:
                _i5.Future<List<_i7.DocumentSearchResult>>.value(
                  <_i7.DocumentSearchResult>[],
                ),
          )
          as _i5.Future<List<_i7.DocumentSearchResult>>);

  @override
  _i5.Future<void> deleteDocument(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDocument, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<int>> downloadDocument(String? documentId) =>
      (super.noSuchMethod(
            Invocation.method(#downloadDocument, [documentId]),
            returnValue: _i5.Future<List<int>>.value(<int>[]),
            returnValueForMissingStub: _i5.Future<List<int>>.value(<int>[]),
          )
          as _i5.Future<List<int>>);

  @override
  _i5.Future<Map<String, dynamic>> uploadThreadDocument(
    String? threadId,
    String? filename,
    _i8.Uint8List? bytes,
    String? contentType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadThreadDocument, [
              threadId,
              filename,
              bytes,
              contentType,
            ]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getThreadDocuments(String? threadId) =>
      (super.noSuchMethod(
            Invocation.method(#getThreadDocuments, [threadId]),
            returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
            returnValueForMissingStub:
                _i5.Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[],
                ),
          )
          as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<void> exportDocument(String? documentId, String? format) =>
      (super.noSuchMethod(
            Invocation.method(#exportDocument, [documentId, format]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
