// Mocks generated by Mockito 5.4.6 from annotations
// in frontend/test/unit/providers/conversation_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:frontend/models/thread.dart' as _i2;
import 'package:frontend/services/ai_service.dart' as _i3;
import 'package:frontend/services/thread_service.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeThread_0 extends _i1.SmartFake implements _i2.Thread {
  _FakeThread_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePaginatedThreads_1 extends _i1.SmartFake
    implements _i2.PaginatedThreads {
  _FakePaginatedThreads_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AIService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAIService extends _i1.Mock implements _i3.AIService {
  @override
  _i4.Stream<_i3.ChatEvent> streamChat(
    String? threadId,
    String? message, {
    bool? artifactGeneration = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #streamChat,
              [threadId, message],
              {#artifactGeneration: artifactGeneration},
            ),
            returnValue: _i4.Stream<_i3.ChatEvent>.empty(),
            returnValueForMissingStub: _i4.Stream<_i3.ChatEvent>.empty(),
          )
          as _i4.Stream<_i3.ChatEvent>);

  @override
  _i4.Future<void> deleteMessage(String? threadId, String? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMessage, [threadId, messageId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [ThreadService].
///
/// See the documentation for Mockito's code generation for more information.
class MockThreadService extends _i1.Mock implements _i5.ThreadService {
  @override
  _i4.Future<List<_i2.Thread>> getThreads(String? projectId) =>
      (super.noSuchMethod(
            Invocation.method(#getThreads, [projectId]),
            returnValue: _i4.Future<List<_i2.Thread>>.value(<_i2.Thread>[]),
            returnValueForMissingStub: _i4.Future<List<_i2.Thread>>.value(
              <_i2.Thread>[],
            ),
          )
          as _i4.Future<List<_i2.Thread>>);

  @override
  _i4.Future<_i2.Thread> createThread(
    String? projectId,
    String? title, {
    String? provider,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createThread,
              [projectId, title],
              {#provider: provider},
            ),
            returnValue: _i4.Future<_i2.Thread>.value(
              _FakeThread_0(
                this,
                Invocation.method(
                  #createThread,
                  [projectId, title],
                  {#provider: provider},
                ),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.Thread>.value(
              _FakeThread_0(
                this,
                Invocation.method(
                  #createThread,
                  [projectId, title],
                  {#provider: provider},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Thread>);

  @override
  _i4.Future<_i2.Thread> getThread(String? threadId) =>
      (super.noSuchMethod(
            Invocation.method(#getThread, [threadId]),
            returnValue: _i4.Future<_i2.Thread>.value(
              _FakeThread_0(this, Invocation.method(#getThread, [threadId])),
            ),
            returnValueForMissingStub: _i4.Future<_i2.Thread>.value(
              _FakeThread_0(this, Invocation.method(#getThread, [threadId])),
            ),
          )
          as _i4.Future<_i2.Thread>);

  @override
  _i4.Future<void> deleteThread(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteThread, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.Thread> renameThread(String? threadId, String? title) =>
      (super.noSuchMethod(
            Invocation.method(#renameThread, [threadId, title]),
            returnValue: _i4.Future<_i2.Thread>.value(
              _FakeThread_0(
                this,
                Invocation.method(#renameThread, [threadId, title]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.Thread>.value(
              _FakeThread_0(
                this,
                Invocation.method(#renameThread, [threadId, title]),
              ),
            ),
          )
          as _i4.Future<_i2.Thread>);

  @override
  _i4.Future<_i2.PaginatedThreads> getGlobalThreads({
    int? page = 1,
    int? pageSize = 25,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getGlobalThreads, [], {
              #page: page,
              #pageSize: pageSize,
            }),
            returnValue: _i4.Future<_i2.PaginatedThreads>.value(
              _FakePaginatedThreads_1(
                this,
                Invocation.method(#getGlobalThreads, [], {
                  #page: page,
                  #pageSize: pageSize,
                }),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.PaginatedThreads>.value(
              _FakePaginatedThreads_1(
                this,
                Invocation.method(#getGlobalThreads, [], {
                  #page: page,
                  #pageSize: pageSize,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.PaginatedThreads>);

  @override
  _i4.Future<_i2.Thread> createGlobalThread({
    String? title,
    String? projectId,
    String? modelProvider,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createGlobalThread, [], {
              #title: title,
              #projectId: projectId,
              #modelProvider: modelProvider,
            }),
            returnValue: _i4.Future<_i2.Thread>.value(
              _FakeThread_0(
                this,
                Invocation.method(#createGlobalThread, [], {
                  #title: title,
                  #projectId: projectId,
                  #modelProvider: modelProvider,
                }),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.Thread>.value(
              _FakeThread_0(
                this,
                Invocation.method(#createGlobalThread, [], {
                  #title: title,
                  #projectId: projectId,
                  #modelProvider: modelProvider,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Thread>);

  @override
  _i4.Future<_i2.Thread> updateThreadMode(String? threadId, String? mode) =>
      (super.noSuchMethod(
            Invocation.method(#updateThreadMode, [threadId, mode]),
            returnValue: _i4.Future<_i2.Thread>.value(
              _FakeThread_0(
                this,
                Invocation.method(#updateThreadMode, [threadId, mode]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.Thread>.value(
              _FakeThread_0(
                this,
                Invocation.method(#updateThreadMode, [threadId, mode]),
              ),
            ),
          )
          as _i4.Future<_i2.Thread>);

  @override
  _i4.Future<_i2.Thread> associateWithProject(
    String? threadId,
    String? projectId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#associateWithProject, [threadId, projectId]),
            returnValue: _i4.Future<_i2.Thread>.value(
              _FakeThread_0(
                this,
                Invocation.method(#associateWithProject, [threadId, projectId]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.Thread>.value(
              _FakeThread_0(
                this,
                Invocation.method(#associateWithProject, [threadId, projectId]),
              ),
            ),
          )
          as _i4.Future<_i2.Thread>);
}
