// Mocks generated by Mockito 5.4.6 from annotations
// in frontend/test/unit/providers/document_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i5;

import 'package:frontend/models/document.dart' as _i2;
import 'package:frontend/services/document_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDocument_0 extends _i1.SmartFake implements _i2.Document {
  _FakeDocument_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DocumentService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDocumentService extends _i1.Mock implements _i3.DocumentService {
  @override
  _i4.Future<_i2.Document> uploadDocument(
    String? projectId,
    List<int>? fileBytes,
    String? filename, {
    void Function(int, int)? onSendProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #uploadDocument,
              [projectId, fileBytes, filename],
              {#onSendProgress: onSendProgress},
            ),
            returnValue: _i4.Future<_i2.Document>.value(
              _FakeDocument_0(
                this,
                Invocation.method(
                  #uploadDocument,
                  [projectId, fileBytes, filename],
                  {#onSendProgress: onSendProgress},
                ),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.Document>.value(
              _FakeDocument_0(
                this,
                Invocation.method(
                  #uploadDocument,
                  [projectId, fileBytes, filename],
                  {#onSendProgress: onSendProgress},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Document>);

  @override
  _i4.Future<List<_i2.Document>> getDocuments(String? projectId) =>
      (super.noSuchMethod(
            Invocation.method(#getDocuments, [projectId]),
            returnValue: _i4.Future<List<_i2.Document>>.value(<_i2.Document>[]),
            returnValueForMissingStub: _i4.Future<List<_i2.Document>>.value(
              <_i2.Document>[],
            ),
          )
          as _i4.Future<List<_i2.Document>>);

  @override
  _i4.Future<_i2.Document> getDocumentContent(String? documentId) =>
      (super.noSuchMethod(
            Invocation.method(#getDocumentContent, [documentId]),
            returnValue: _i4.Future<_i2.Document>.value(
              _FakeDocument_0(
                this,
                Invocation.method(#getDocumentContent, [documentId]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.Document>.value(
              _FakeDocument_0(
                this,
                Invocation.method(#getDocumentContent, [documentId]),
              ),
            ),
          )
          as _i4.Future<_i2.Document>);

  @override
  _i4.Future<List<_i3.DocumentSearchResult>> searchDocuments(
    String? projectId,
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchDocuments, [projectId, query]),
            returnValue: _i4.Future<List<_i3.DocumentSearchResult>>.value(
              <_i3.DocumentSearchResult>[],
            ),
            returnValueForMissingStub:
                _i4.Future<List<_i3.DocumentSearchResult>>.value(
                  <_i3.DocumentSearchResult>[],
                ),
          )
          as _i4.Future<List<_i3.DocumentSearchResult>>);

  @override
  _i4.Future<void> deleteDocument(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDocument, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<int>> downloadDocument(String? documentId) =>
      (super.noSuchMethod(
            Invocation.method(#downloadDocument, [documentId]),
            returnValue: _i4.Future<List<int>>.value(<int>[]),
            returnValueForMissingStub: _i4.Future<List<int>>.value(<int>[]),
          )
          as _i4.Future<List<int>>);

  @override
  _i4.Future<Map<String, dynamic>> uploadThreadDocument(
    String? threadId,
    String? filename,
    _i5.Uint8List? bytes,
    String? contentType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadThreadDocument, [
              threadId,
              filename,
              bytes,
              contentType,
            ]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getThreadDocuments(String? threadId) =>
      (super.noSuchMethod(
            Invocation.method(#getThreadDocuments, [threadId]),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
            returnValueForMissingStub:
                _i4.Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[],
                ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<void> exportDocument(String? documentId, String? format) =>
      (super.noSuchMethod(
            Invocation.method(#exportDocument, [documentId, format]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
