// Mocks generated by Mockito 5.4.6 from annotations
// in frontend/test/widget/chats_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i7;

import 'package:frontend/models/thread.dart' as _i3;
import 'package:frontend/models/thread_sort.dart' as _i5;
import 'package:frontend/providers/chats_provider.dart' as _i2;
import 'package:frontend/providers/provider_provider.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ChatsProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatsProvider extends _i1.Mock implements _i2.ChatsProvider {
  @override
  List<_i3.Thread> get threads =>
      (super.noSuchMethod(
            Invocation.getter(#threads),
            returnValue: <_i3.Thread>[],
            returnValueForMissingStub: <_i3.Thread>[],
          )
          as List<_i3.Thread>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isInitialized =>
      (super.noSuchMethod(
            Invocation.getter(#isInitialized),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  int get total =>
      (super.noSuchMethod(
            Invocation.getter(#total),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  bool get hasMore =>
      (super.noSuchMethod(
            Invocation.getter(#hasMore),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  String get searchQuery =>
      (super.noSuchMethod(
            Invocation.getter(#searchQuery),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#searchQuery),
            ),
            returnValueForMissingStub: _i4.dummyValue<String>(
              this,
              Invocation.getter(#searchQuery),
            ),
          )
          as String);

  @override
  _i5.ThreadSortOption get sortOption =>
      (super.noSuchMethod(
            Invocation.getter(#sortOption),
            returnValue: _i5.ThreadSortOption.newest,
            returnValueForMissingStub: _i5.ThreadSortOption.newest,
          )
          as _i5.ThreadSortOption);

  @override
  List<_i3.Thread> get filteredThreads =>
      (super.noSuchMethod(
            Invocation.getter(#filteredThreads),
            returnValue: <_i3.Thread>[],
            returnValueForMissingStub: <_i3.Thread>[],
          )
          as List<_i3.Thread>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void setSearchQuery(String? query) => super.noSuchMethod(
    Invocation.method(#setSearchQuery, [query]),
    returnValueForMissingStub: null,
  );

  @override
  void setSortOption(_i5.ThreadSortOption? option) => super.noSuchMethod(
    Invocation.method(#setSortOption, [option]),
    returnValueForMissingStub: null,
  );

  @override
  void clearSearch() => super.noSuchMethod(
    Invocation.method(#clearSearch, []),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> loadThreads() =>
      (super.noSuchMethod(
            Invocation.method(#loadThreads, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> loadMoreThreads() =>
      (super.noSuchMethod(
            Invocation.method(#loadMoreThreads, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i3.Thread?> createNewChat({String? modelProvider}) =>
      (super.noSuchMethod(
            Invocation.method(#createNewChat, [], {
              #modelProvider: modelProvider,
            }),
            returnValue: _i6.Future<_i3.Thread?>.value(),
            returnValueForMissingStub: _i6.Future<_i3.Thread?>.value(),
          )
          as _i6.Future<_i3.Thread?>);

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ProviderProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockProviderProvider extends _i1.Mock implements _i8.ProviderProvider {
  @override
  String get selectedProvider =>
      (super.noSuchMethod(
            Invocation.getter(#selectedProvider),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#selectedProvider),
            ),
            returnValueForMissingStub: _i4.dummyValue<String>(
              this,
              Invocation.getter(#selectedProvider),
            ),
          )
          as String);

  @override
  List<String> get providers =>
      (super.noSuchMethod(
            Invocation.getter(#providers),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i6.Future<void> setProvider(String? provider) =>
      (super.noSuchMethod(
            Invocation.method(#setProvider, [provider]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
