// Mocks generated by Mockito 5.4.6 from annotations
// in frontend/test/widget/conversation_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i7;

import 'package:flutter/material.dart' as _i6;
import 'package:frontend/models/message.dart' as _i3;
import 'package:frontend/providers/conversation_provider.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ConversationProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockConversationProvider extends _i1.Mock
    implements _i2.ConversationProvider {
  @override
  List<_i3.Message> get messages =>
      (super.noSuchMethod(
            Invocation.getter(#messages),
            returnValue: <_i3.Message>[],
            returnValueForMissingStub: <_i3.Message>[],
          )
          as List<_i3.Message>);

  @override
  String get streamingText =>
      (super.noSuchMethod(
            Invocation.getter(#streamingText),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#streamingText),
            ),
            returnValueForMissingStub: _i4.dummyValue<String>(
              this,
              Invocation.getter(#streamingText),
            ),
          )
          as String);

  @override
  bool get isStreaming =>
      (super.noSuchMethod(
            Invocation.getter(#isStreaming),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get loading =>
      (super.noSuchMethod(
            Invocation.getter(#loading),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isNotFound =>
      (super.noSuchMethod(
            Invocation.getter(#isNotFound),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get canRetry =>
      (super.noSuchMethod(
            Invocation.getter(#canRetry),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i5.Future<void> loadThread(String? threadId) =>
      (super.noSuchMethod(
            Invocation.method(#loadThread, [threadId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> sendMessage(String? content) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [content]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void clearConversation() => super.noSuchMethod(
    Invocation.method(#clearConversation, []),
    returnValueForMissingStub: null,
  );

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  void retryLastMessage() => super.noSuchMethod(
    Invocation.method(#retryLastMessage, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> deleteMessage(
    _i6.BuildContext? context,
    String? threadId,
    String? messageId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMessage, [context, threadId, messageId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> associateWithProject(String? projectId) =>
      (super.noSuchMethod(
            Invocation.method(#associateWithProject, [projectId]),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
