// Mocks generated by Mockito 5.4.6 from annotations
// in frontend/test/widget/document_list_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i6;

import 'package:frontend/models/document.dart' as _i3;
import 'package:frontend/providers/document_provider.dart' as _i2;
import 'package:frontend/services/document_service.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [DocumentProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockDocumentProvider extends _i1.Mock implements _i2.DocumentProvider {
  @override
  List<_i3.Document> get documents =>
      (super.noSuchMethod(
            Invocation.getter(#documents),
            returnValue: <_i3.Document>[],
            returnValueForMissingStub: <_i3.Document>[],
          )
          as List<_i3.Document>);

  @override
  bool get loading =>
      (super.noSuchMethod(
            Invocation.getter(#loading),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  double get uploadProgress =>
      (super.noSuchMethod(
            Invocation.getter(#uploadProgress),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  bool get uploading =>
      (super.noSuchMethod(
            Invocation.getter(#uploading),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i4.Future<void> loadDocuments(String? projectId) =>
      (super.noSuchMethod(
            Invocation.method(#loadDocuments, [projectId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> uploadDocument(
    String? projectId,
    List<int>? fileBytes,
    String? filename,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadDocument, [
              projectId,
              fileBytes,
              filename,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> selectDocument(String? documentId) =>
      (super.noSuchMethod(
            Invocation.method(#selectDocument, [documentId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void clearSelectedDocument() => super.noSuchMethod(
    Invocation.method(#clearSelectedDocument, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<List<_i5.DocumentSearchResult>> searchDocuments(
    String? projectId,
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchDocuments, [projectId, query]),
            returnValue: _i4.Future<List<_i5.DocumentSearchResult>>.value(
              <_i5.DocumentSearchResult>[],
            ),
            returnValueForMissingStub:
                _i4.Future<List<_i5.DocumentSearchResult>>.value(
                  <_i5.DocumentSearchResult>[],
                ),
          )
          as _i4.Future<List<_i5.DocumentSearchResult>>);

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
