// Mocks generated by Mockito 5.4.6 from annotations
// in frontend/test/widget/project_list_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i5;

import 'package:frontend/models/project.dart' as _i3;
import 'package:frontend/providers/project_provider.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ProjectProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockProjectProvider extends _i1.Mock implements _i2.ProjectProvider {
  @override
  List<_i3.Project> get projects =>
      (super.noSuchMethod(
            Invocation.getter(#projects),
            returnValue: <_i3.Project>[],
            returnValueForMissingStub: <_i3.Project>[],
          )
          as List<_i3.Project>);

  @override
  bool get loading =>
      (super.noSuchMethod(
            Invocation.getter(#loading),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i4.Future<void> loadProjects() =>
      (super.noSuchMethod(
            Invocation.method(#loadProjects, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i3.Project?> createProject(String? name, String? description) =>
      (super.noSuchMethod(
            Invocation.method(#createProject, [name, description]),
            returnValue: _i4.Future<_i3.Project?>.value(),
            returnValueForMissingStub: _i4.Future<_i3.Project?>.value(),
          )
          as _i4.Future<_i3.Project?>);

  @override
  _i4.Future<void> selectProject(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#selectProject, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i3.Project?> updateProject(
    String? id,
    String? name,
    String? description,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateProject, [id, name, description]),
            returnValue: _i4.Future<_i3.Project?>.value(),
            returnValueForMissingStub: _i4.Future<_i3.Project?>.value(),
          )
          as _i4.Future<_i3.Project?>);

  @override
  void clearSelection() => super.noSuchMethod(
    Invocation.method(#clearSelection, []),
    returnValueForMissingStub: null,
  );

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
