// Mocks generated by Mockito 5.4.6 from annotations
// in frontend/test/widget/thread_list_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i8;

import 'package:flutter/material.dart' as _i7;
import 'package:frontend/models/thread.dart' as _i2;
import 'package:frontend/models/thread_sort.dart' as _i5;
import 'package:frontend/providers/thread_provider.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeThread_0 extends _i1.SmartFake implements _i2.Thread {
  _FakeThread_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ThreadProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockThreadProvider extends _i1.Mock implements _i3.ThreadProvider {
  @override
  List<_i2.Thread> get threads =>
      (super.noSuchMethod(
            Invocation.getter(#threads),
            returnValue: <_i2.Thread>[],
            returnValueForMissingStub: <_i2.Thread>[],
          )
          as List<_i2.Thread>);

  @override
  bool get loading =>
      (super.noSuchMethod(
            Invocation.getter(#loading),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  String get searchQuery =>
      (super.noSuchMethod(
            Invocation.getter(#searchQuery),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#searchQuery),
            ),
            returnValueForMissingStub: _i4.dummyValue<String>(
              this,
              Invocation.getter(#searchQuery),
            ),
          )
          as String);

  @override
  _i5.ThreadSortOption get sortOption =>
      (super.noSuchMethod(
            Invocation.getter(#sortOption),
            returnValue: _i5.ThreadSortOption.newest,
            returnValueForMissingStub: _i5.ThreadSortOption.newest,
          )
          as _i5.ThreadSortOption);

  @override
  List<_i2.Thread> get filteredThreads =>
      (super.noSuchMethod(
            Invocation.getter(#filteredThreads),
            returnValue: <_i2.Thread>[],
            returnValueForMissingStub: <_i2.Thread>[],
          )
          as List<_i2.Thread>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i6.Future<void> loadThreads(String? projectId) =>
      (super.noSuchMethod(
            Invocation.method(#loadThreads, [projectId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i2.Thread> createThread(
    String? projectId,
    String? title, {
    String? provider,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createThread,
              [projectId, title],
              {#provider: provider},
            ),
            returnValue: _i6.Future<_i2.Thread>.value(
              _FakeThread_0(
                this,
                Invocation.method(
                  #createThread,
                  [projectId, title],
                  {#provider: provider},
                ),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Thread>.value(
              _FakeThread_0(
                this,
                Invocation.method(
                  #createThread,
                  [projectId, title],
                  {#provider: provider},
                ),
              ),
            ),
          )
          as _i6.Future<_i2.Thread>);

  @override
  _i6.Future<void> selectThread(String? threadId) =>
      (super.noSuchMethod(
            Invocation.method(#selectThread, [threadId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i2.Thread?> renameThread(String? threadId, String? title) =>
      (super.noSuchMethod(
            Invocation.method(#renameThread, [threadId, title]),
            returnValue: _i6.Future<_i2.Thread?>.value(),
            returnValueForMissingStub: _i6.Future<_i2.Thread?>.value(),
          )
          as _i6.Future<_i2.Thread?>);

  @override
  void clearThreads() => super.noSuchMethod(
    Invocation.method(#clearThreads, []),
    returnValueForMissingStub: null,
  );

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  void setSearchQuery(String? query) => super.noSuchMethod(
    Invocation.method(#setSearchQuery, [query]),
    returnValueForMissingStub: null,
  );

  @override
  void setSortOption(_i5.ThreadSortOption? option) => super.noSuchMethod(
    Invocation.method(#setSortOption, [option]),
    returnValueForMissingStub: null,
  );

  @override
  void clearSearch() => super.noSuchMethod(
    Invocation.method(#clearSearch, []),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> deleteThread(_i7.BuildContext? context, String? threadId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteThread, [context, threadId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
